name: Java CI with Maven and MySQL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: hookah_shop
          MYSQL_USER: sammy
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_AUTH_PLUGIN: mysql_native_password
          MYSQL_ALLOW_EMPTY_PASSWORD: yes  # Allow empty password for root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Configure MySQL User
      run: |
        mysql -h 127.0.0.1 -u root --password= ${{secrets.MYSQL_PASSWORDROOT}} -e "ALTER USER 'sammy'@'%' IDENTIFIED WITH mysql_native_password BY '${{ secrets.MYSQL_PASSWORD }}'; FLUSH PRIVILEGES;"

    - name: Build and test with Maven
      run: mvn -B verify

    - name: Package WAR file
      run: mvn -B package --file pom.xml

    # Additional steps if needed, such as deploying the WAR file
